// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABTP-IZMM1TGWyzf4em__TpJQR2u2aMhY',
    appId: '1:648461228472:web:2fa180a4082c4f81ac174d',
    messagingSenderId: '648461228472',
    projectId: 'common-groundsg10mda-6aae6',
    authDomain: 'common-groundsg10mda-6aae6.firebaseapp.com',
    storageBucket: 'common-groundsg10mda-6aae6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRqM1RSOCXD4cdv3Y6xuLrOze5-CTOwgQ',
    appId: '1:648461228472:android:73225f2cc56ac0dbac174d',
    messagingSenderId: '648461228472',
    projectId: 'common-groundsg10mda-6aae6',
    storageBucket: 'common-groundsg10mda-6aae6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaLGsg8DtjVewPhGs-VjUJ0rdmSYADoHo',
    appId: '1:648461228472:ios:dac445177639bcd9ac174d',
    messagingSenderId: '648461228472',
    projectId: 'common-groundsg10mda-6aae6',
    storageBucket: 'common-groundsg10mda-6aae6.firebasestorage.app',
    iosBundleId: 'com.group13.commongrounds.commongrounds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaLGsg8DtjVewPhGs-VjUJ0rdmSYADoHo',
    appId: '1:648461228472:ios:dac445177639bcd9ac174d',
    messagingSenderId: '648461228472',
    projectId: 'common-groundsg10mda-6aae6',
    storageBucket: 'common-groundsg10mda-6aae6.firebasestorage.app',
    iosBundleId: 'com.group13.commongrounds.commongrounds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABTP-IZMM1TGWyzf4em__TpJQR2u2aMhY',
    appId: '1:648461228472:web:dbeada7de3b04981ac174d',
    messagingSenderId: '648461228472',
    projectId: 'common-groundsg10mda-6aae6',
    authDomain: 'common-groundsg10mda-6aae6.firebaseapp.com',
    storageBucket: 'common-groundsg10mda-6aae6.firebasestorage.app',
  );
}
